### ISSUE TITLE
Implement redirects

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#10]
Determine if we are implementing in [Gatsby](https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects-and-Rewrites) or in Akamai. 

If we can get redirects to work in [gatsby-node](https://github.com/NCIOCPL/gatsby-pcp/blob/develop/gatsby-node.js) I am happy with that. It keeps our code more compact and I don't think we'll get enough traffic for it to be an issue.

**Comment by SupriyaSaxena0605** [comment]
@jfrank-nih Tested these below redirects. They look good:
https://prescancerpanel-test.cancer.gov/reports/2016/access-cost-drugs/
https://prescancerpanel-test.cancer.gov/reports/2020/lung/
https://prescancerpanel-test.cancer.gov/reports/2021/innovations/
https://prescancerpanel-test.cancer.gov/reports/2020/colorectal/
https://prescancerpanel-test.cancer.gov/reports/2020/cervical/
https://prescancerpanel-test.cancer.gov/reports/2020/breast/
https://prescancerpanel-test.cancer.gov/reports/2016/emerging-opportunities/
https://prescancerpanel-test.cancer.gov/reports/2017/pricing-and-payment-strategies/
https://prescancerpanel-test.cancer.gov/reports/2014/engaging-patients/
https://prescancerpanel-test.cancer.gov/reports/2015/health-data/
https://prescancerpanel-test.cancer.gov/reports/2015/connected-cancer-patient/
