### ISSUE TITLE
PCP Design Assets

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#103]
- [ ] Provide updated infographics with new fonts to the website
- [ ] Update PCP timeline with new member information
- [ ] Provide hero images for site

### Timeline Update: 

Update the Panel timeline and add the following members. Attached is a copy of their headshots. 

- John P. Williams, MD (Chair)  
Start Date: 3/15/2020
End Date: 01/31/2023

![Image](https://github.com/NCIOCPL/gatsby-pcp/assets/80473282/13f4be25-27fe-4c94-825b-7584025c4795)

- Edith P. Mitchell, MD (Member) 
Start Date: 2/16/2020
End Date: 01/31/2023
 

![Image](https://github.com/NCIOCPL/gatsby-pcp/assets/80473282/6580eb68-ef06-434f-8b70-2f91779c12bf)

- Robert A. Ingram (Member) 
Start Date: 8/30/2020
End Date: 01/31/2023

![Image](https://github.com/NCIOCPL/gatsby-pcp/assets/80473282/4b6fdee8-ce53-4320-b91d-70962826d41b)

**Comment by dcvijanovic1k** [comment]
Hi @santwuma  - here's the updated graphic. Please let me know if you have any questions. Thanks!

![PCP-pastmembers-update-051923](https://github.com/NCIOCPL/gatsby-pcp/assets/102183929/2f85260d-8bf2-4331-85e9-d0afa962a8ce)

**Comment by dcvijanovic1k** [comment]
Hi again @santwuma - here's an updated graphic, per the edits we just heard from PCP in our meeting. 
![PCP-pastmembers-update-051923_V2](https://github.com/NCIOCPL/gatsby-pcp/assets/102183929/5169edc1-db37-43bd-9516-d5c700a58edb)

**Comment by santwuma** [comment]
@erikscottmeyer updated graphic for past members - can you please post this on the site?

**Comment by erikscottmeyer** [comment]
@dcvijanovic1k Could you make a mobile version of this please?

**Comment by dcvijanovic1k** [comment]
Hi @erikscottmeyer - here's a mobile version of the image for you; please let me know if you need any additional edits. Thanks!
![PCP-pastmembers-update-051923-mobile_V2](https://github.com/NCIOCPL/gatsby-pcp/assets/102183929/a33ac0f7-45b2-4723-937e-10870a930af6)
