### ISSUE TITLE
Fix accessibility errors in reports

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#115]
There are a number of accessibility errors in the old `reports/` folder. This is not technically our code, but we would need to fix to launch a 508 compliant site.

Note: when doing this we would want to remove the **/report/** exclusion from the `.pa111yci.js` file. 

Here's what `npm run test:a11y` shows: [pa11y errors.txt](https://github.com/NCIOCPL/gatsby-pcp/files/11574257/pa11y.errors.txt).

This really comes down to a smaller set of errors:

````
• This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit buttons are INPUT elements with type
````

The search forms need a `<button>Go</button>` inserted after them.

---

````
• This link points to a named anchor "addtoany" within the document, but no anchor exists with that name.
• Anchor element found with a valid href attribute, but no link content has been supplied.
• Anchor element found with no link content and no name and/or ID attribute.
````

This may be a bit harder as it's generated by their sharing script. We could add a rule to ignore it in the tests if needed.

---

````
• Duplicate id attribute value "blueButton1" found on the web page.
• Duplicate id attribute value "blueButton2" found on the web page.
• Duplicate id attribute value "blueButton3" found on the web page.
• Duplicate id attribute value "blueButton4" found on the web page.
• Duplicate id attribute value "grayButton1" found on the web page.
• Duplicate id attribute value "grayButton2" found on the web page.
• Duplicate id attribute value "grayButton3" found on the web page.
• Duplicate id attribute value "grayButton4" found on the web page.
````

De-dupe the button ID duplicates. I think they're mobile views.

---

````
• The language specified in the lang attribute of the document element does not appear to be well-formed.
````

Fix the language attribute.

---

````
• This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.95:1.
• This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.94:1.
````

Fix the contrast.

---

````
• Duplicate id attribute value "backToTopAnchor" found on the web page.
````

Remove duplicate IDs.

---

````
• Img element missing an alt attribute. Use the alt attribute to specify a short text alternative.
`````

Add `alt` attributes.

---

````
• This link points to a named anchor "fig4" within the document, but no anchor exists with that name.
````

Fix or remove link.

**Comment by jfrank-nih** [comment]
@santwuma, there's nothing terribly difficult to do in here. It would just be time for someone to go through it all. I think the only real challenge is the sharing toolbar but we may be able to add an exclusion for that.

Someone should check with the client as to whether they want to fix these or ignore them, or whether we should fix them.

I would _like_ to get accessibility testing turned on for all HTML files so ideally _someone_ fixes them.

**Comment by santwuma** [comment]
PCP confirmed we may proceed with updates on 5/30
