### ISSUE TITLE
Enabler: Style Pages 

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#15]
Style pages using react components with SASS styles. Global styles can be inherited from the main CSS.

## Sub-Tasks
- [ ] Home
- [ ] Members
    - Individual members pages
- [ ] About
    - Sub-pages
- [ ] Reports & Meetings

## Resources
[Mural](https://app.mural.co/t/worklifepage1864/m/worklifepage1864/1665585689544/22bc12c75257b9a87d068eb03dbda96d4f61d72e?sender=u391897c2e974e80931994272)

- ...

**Comment by jfrank-nih** [comment]
I'm going to close this out and we'll open smaller tickets for remaining tasks.
