### ISSUE TITLE
Static reports with text overlapping

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#163]
Identify and fix the overlapping text on these pages:

- https://prescancerpanel-test.cancer.gov/report/connectedhealth/Part2Obj2.html 
- https://prescancerpanel-test.cancer.gov/report/connectedhealth/Part2Obj4.html 
- https://prescancerpanel-test.cancer.gov/report/connectedhealth/Part2Obj5.html

**Comment by erikscottmeyer** [comment]
this problem was caused by missing jquery libraries (anythingslider).  I also addressed: link color (bolded), Meetings with empty links, Font size for report titles (increased from 2.5 to 3)
