### ISSUE TITLE
Convert  PCP mobile view  navigation to Hamburger 

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#185]
Make the PCP site use a hamburger menu on mobile sites so as to prevent awkward menu wrapping on small screens.

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer @santwuma 
Hamburger menu opens up leaving lot of space before the actual menu displays
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/33aff179-40f0-4d96-9451-a03744a319ae)

**Comment by jfrank-nih** [comment]
Ah, this only happens if you are scrolled down the page. It must be attached to the absolute height of the hamburger button from the top of the page.

**Comment by SupriyaSaxena0605** [comment]
For me, this is happening without scrolling

**Comment by santwuma** [comment]
@erikscottmeyer can you please look into this?

**Comment by erikscottmeyer** [comment]
@santwuma I am looking into it.

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer @santwuma This PR looks good
