### ISSUE TITLE
PCP Website updates | September 7 NCP Meeting

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/gatsby-pcp#201]
Requested by PCP team on 8/31:

Could you please post the attached participant list and agenda for the Sept 7th meeting: https://prescancerpanel.cancer.gov/ncp/meetings/.

Please complete updated by EOD 9/6

[Sept 7 NCP PUBLIC Meeting Agenda_2023.08.25.docx](https://github.com/NCIOCPL/gatsby-pcp/files/12488802/Sept.7.NCP.PUBLIC.Meeting.Agenda_2023.08.25.docx)
[Sept 7 NCP Participant List.docx](https://github.com/NCIOCPL/gatsby-pcp/files/12488803/Sept.7.NCP.Participant.List.docx)

**Comment by santwuma** [comment]
For the September 7 PCP agenda page:

Could you add the vbrick link at the top of the page[: https://nci.rev.vbrick.com/#/event-registration/6cfe1caa-6bce-4f62-9124-d8fd1b2cbbba](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnci.rev.vbrick.com%2F%23%2Fevent-registration%2F6cfe1caa-6bce-4f62-9124-d8fd1b2cbbba&data=05%7C01%7Czola.shaw%40nih.gov%7C6c7a9977c5464588ab9b08dbaef31825%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638296131325017545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bx3IgdKWpIgGZ94dtcNLvg8%2BoiFpxCbn8CTqgvCxPXM%3D&reserved=0)
Could you also change where the agenda is posted on this page [Meetings - President's Cancer Panel](https://prescancerpanel.cancer.gov/ncp/meetings/)

Please add the following sentence with the agenda link after the first [paragraph](https://prescancerpanel.cancer.gov/ncp/meetings/), “The agenda and participant list is available here.”
