### ISSUE TITLE
PCP | Website updates | NCP September 7 meeting

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#209]

**Comment by santwuma** [comment]
Suggested change

Remove the following sentence, “The September 7, 2023 virtual meeting is open to the public. To attend, click here.” - located at the bottom of our ‘Meetings’ page:  (see attached for location)

https://prescancerpanel.cancer.gov/ncp/meetings/




Add “Watch the recording here.” at the bottom of our ‘Meetings’ page (https://prescancerpanel.cancer.gov/ncp/meetings/)  & hyperlink with: [https://nci.rev.vbrick.com/#/videos/ca9bf067-ba4f-4dbe-a2fe-e4ad79068adc](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnci.rev.vbrick.com%2F%23%2Fvideos%2Fca9bf067-ba4f-4dbe-a2fe-e4ad79068adc&data=05%7C01%7Czola.shaw%40nih.gov%7C01cc52b34ebd4b459c0508dbb48e7cd1%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638302296292046189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nxgy4V8Xjy5aA1W3KaxiSKWcayACsvlUAorcO096dFM%3D&reserved=0)

Quick question, is there any way that we could add a camera icon before, “Watch the recording here” (attached)?

**Comment by santwuma** [comment]
Could you please include the recording on the page by tomorrow? We can provide the camera icon later next week. PCP let me know the priority is getting the recording posted
 

Could you please make the following edits
https://prescancerpanel.cancer.gov/ncp/meetings/

**Remove, “Mark your calendars! The initial stakeholder meeting will be held virtually on Thursday, September 7, 2023.”
Add “The initial stakeholder meeting concluded on September 7th, 2023. To view the recording, please click here” hyperlink with: [https://nci.rev.vbrick.com/#/videos/ca9bf067-ba4f-4dbe-a2fe-e4ad79068adc](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnci.rev.vbrick.com%2F%23%2Fvideos%2Fca9bf067-ba4f-4dbe-a2fe-e4ad79068adc&data=05%7C01%7Czola.shaw%40nih.gov%7Cd896c324a0df47be597308dbbac6c51b%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638309135096106833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KvFmlK8fDBHGyN6hS4WXtff3N%2BZhC%2Fju0z5KKuLPNgo%3D&reserved=0)**. Please make sure this text appears at the top of the page.

**Comment by SupriyaSaxena0605** [comment]
@santwuma @jfrank-nih @erikscottmeyer looks good in dev and test
