### ISSUE TITLE
PCP| Website Update| Post Sept 7 Meeting blog

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#210]
The Panel is working on a new blog to highlight the Sept 7th meeting. Could you please get the page ready for posting? I attached a draft of the blog the team to work with while the PCP team finalizes the blog.

PCP would like for blog to be up before Sept 30th. Let me know if you have any questions.

[Final_ PCP_Blog_NCP Meeting_2023.9.21.docx](https://github.com/NCIOCPL/gatsby-pcp/files/12718400/Final_.PCP_Blog_NCP.Meeting_2023.9.21.docx)

**Comment by santwuma** [comment]
Title: National Cancer Plan Stakeholder Meeting: Cancer Community Comes Together to Share Ideas for Progress
Image: 
![Blog 5 Posts NCP Stakeholder Meeting (Sept 7) (800 × 800 px)](https://github.com/NCIOCPL/gatsby-pcp/assets/80473282/72ed6239-cf43-490a-bc04-c453e11ba49f)

In addition, they’d like to change the third feature card on their homepage with the following:
Title: National Cancer Plan Stakeholder Meeting
Text: On September 7th, the Panel convened a meeting with stakeholders from across the cancer community to highlight progress towards the National Cancer Plan’s goals & discuss opportunities to accelerate progress. Check out our latest blog for a meeting recap and learn more about the Panel’s next steps.
Image: Attached.

@erikscottmeyer

**Comment by SupriyaSaxena0605** [comment]
@santwuma  @erikscottmeyer the paragraph with bullet points are not displayed correctly 
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/cc5b6b51-60fa-4dde-b921-85ff04a8dacf)

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer New feature card on homepage has different text than what is mentioned by @santwuma in above comment
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/7db1866f-a6a0-4505-bff7-bb407b618a88)

**Comment by santwuma** [comment]
They just provided us with updated text to accompany the feature card instead of the language sent yesterday.: 
•	On September 7th, the Panel convened a meeting with stakeholders from across the cancer community to highlight progress towards the National Cancer Plan’s goals and discuss opportunities for improvement. Check out our latest blog for a meeting recap and learn more about the Panel’s next steps.

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer @santwuma Verified the updates on Dev and Test. Looks good
