### ISSUE TITLE
PCP | Website updates | NCP September 7 meeting

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#211]
I have a few more edits for this page (https://prescancerpanel.cancer.gov/ncp/meetings/):

Instead of the sentence, "This meeting will consist of presentations..." please replace with "This meeting consisted of presentations...."

Also, I don't think we need the last bit of text on that page:

This meeting will be led by President’s Cancer Panel members Dr. Elizabeth Jaffee, Dr. Carol Brown, and Dr. Mitchel Berger.

[Watch the recording here.](https://nci.rev.vbrick.com/#/videos/ca9bf067-ba4f-4dbe-a2fe-e4ad79068adc).

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer @santwuma The updates look good on Dev 
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/4089fd63-f07f-4d94-be41-b8ce71d45d08)

**Comment by SupriyaSaxena0605** [comment]
@santwuma @erikscottmeyer Verified the updates on Dev and Test. Looks good
