### ISSUE TITLE
Simplify image inclusion and styles

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#227]
### Issue description

We currently have multiple different image inclusion methods.

- `image-with-caption`: ImageWithCaption
- `image-with-class`: ImageWithClass
- `picture-with-quotes`: PictureWithQuotes
- `responsive-image`: ResponsiveImage

I'd like to simplify this to:
- As few tags as possible
- The least markup possible (ideally _just_ the markdown itself whenever we can)

We'll create a documentation page on how to use them in combination with each other to get the results we want. Changes we make should look substantially similar to current formats but don't have to be _identical_.

**_We should also move off of gatsby-image_**, [which is deprecated](https://www.gatsbyjs.com/plugins/gatsby-image/), to gatsby-plugin-image. See also #219.

### What's the proposed change?

- `image-with-caption`: gatsby-remark-images plugin has attributes `showCaptions` and `markdownCaptions` that can take a title input and use it as the caption. ([Docs](https://www.gatsbyjs.com/plugins/gatsby-remark-images/), [example](https://dev.to/stephencweiss/markdown-image-titles-and-alt-text-5fi1)) We'd just need to style the caption to match current code. Then we could just use the markdown in the content.
- `image-with-class`: We could either...
    - Replace this with just documentation to wrap a `<div class="X/Y/Z">` around the markdown image tag, or
    - Update `<image-with-class>` to have the `className` attribute but instead of `src` and `alt` it would just wrap around the standard markdown syntax. That would allow it to be used with the caption syntax easily as well.
    
    ````
    <image-with-class className="X">
    ![Alt](/path/to/img.jpg “image title”)
    </image-with-class>
    ````
    
- `picture-with-quotes` is only used in a few early blogs. Can we somehow use the other styles to replicate it? Maybe an `<image-with-class>` tag and a markdown caption combined? The look does not have to be exactly what we currently have.
- `responsive-image`: No real way to replicate this with other tags leave as-is. But are we able to remove the `<div>` [around it](https://github.com/NCIOCPL/gatsby-pcp/blob/1ae408e6289a90529dee327fdc40c0a145a87725/content/members/index.md?plain=1#L33) without introducing any problems?

**Comment by erikscottmeyer** [comment]
image-with-caption: these changes should be fine

**Comment by erikscottmeyer** [comment]
picture-with-quotes : we could rig something like this up; obviously it would be easier if we didn't need it to replicate what this does and simplified rendering

**Comment by jfrank-nih** [comment]
Closing because PCP has moved to the digital platform.
