### ISSUE TITLE
PCP | Website updates | NCP Content Changes

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#259]
Please make the attached updates to https://prescancerpanel.cancer.gov/ncp/ 

Please note there are comments included in the word document (attached)

Other attachments:

Image that will go under the Public Meetings page
PDF of the meeting summary that will go on the September 7, 2023 page.

When do you anticipate completing these changes? I would like to let the PCP know in advance.

**Attachment:** 

![Image](https://github.com/NCIOCPL/gatsby-pcp/assets/80473282/3b554e83-017a-4420-ab15-eb785c61a30c)

[September 7 NCP Meeting Summary_112423_508.pdf](https://github.com/NCIOCPL/gatsby-pcp/files/13665791/September.7.NCP.Meeting.Summary_112423_508.pdf)

[12.12.2023_NCP Content.docx](https://github.com/NCIOCPL/gatsby-pcp/files/13665792/12.12.2023_NCP.Content.docx)

**Comment by meglake** [comment]
Hi @erikscottmeyer, please see feedback below from client with some changes to the page:
1. Page: https://prescancerpanel-dev.cancer.gov/pr-260/ncp/ 

- [ ] Decrease the size of the “National Cancer Plan” box to reduce spacing between the first paragraph and "The Panel looks forward to..." statement.  

2. Page: https://prescancerpanel-dev.cancer.gov/pr-260/ncp/meetings/

- [ ] Make the image (attached) small and have it sit to the right of the text. 
See example here of the layout the team wants  https://prescancerpanel.cancer.gov/about/blogs/leveraging-technology-to-enhance-patient-navigation/
![September 7_Meeting Screenshot_401 x 357](https://github.com/NCIOCPL/gatsby-pcp/assets/41208873/45afdff4-a64c-4ff9-b9e0-52c5fc918201)

**Comment by meglake** [comment]
The Client requested one last edit and then the page updates can go live:

- [ ] Please update the hyperlink in the first sentence of this page: https://prescancerpanel-dev.cancer.gov/pr-260/ncp/ to go to this link: https://nationalcancerplan.cancer.gov/
