### ISSUE TITLE
PCP | Drupal Update | Sept. 12-13 Meeting Materials

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#288]
Ticket details in JIRA request: https://tracker.nci.nih.gov/browse/CGOV-22002 

**PCP would like to go live on Wednesday 9/4**

**Comment by meglake** [comment]
@erikscottmeyer, Tula has responded with feedback from PCP. Attaching the document with PCP's comments along with updated agendas and participants lists, each of which includes highlights on the specific text that needs to be changed. Please take a look and let me know if you have any questions. I noticed that they want to keep the feature card as is. Is this possible to leave as if (even though it doesn't fit the same style as the other two feature cards on the page) or should I push to get an updated image in the correct aspect ratio?
[Panel Website Reviews_NCP Mtg Page.docx](https://github.com/user-attachments/files/16850489/Panel.Website.Reviews_NCP.Mtg.Page.docx)
[09.13 NCP.MtgParticipant List (UPDATED).docx](https://github.com/user-attachments/files/16850491/09.13.NCP.MtgParticipant.List.UPDATED.docx)
[09.12 NCP.MtgParticipant List (UPDATED).docx](https://github.com/user-attachments/files/16850492/09.12.NCP.MtgParticipant.List.UPDATED.docx)
[ForWebPosting_09.12_NCP.MtgAgenda (UPDATED).docx](https://github.com/user-attachments/files/16850493/ForWebPosting_09.12_NCP.MtgAgenda.UPDATED.docx)
[ForWebPosting_09.13_NCP.MtgAgenda (UPDATED).docx](https://github.com/user-attachments/files/16850494/ForWebPosting_09.13_NCP.MtgAgenda.UPDATED.docx)

**Comment by meglake** [comment]
V2 of 9/12 agenda just sent to us on the Jira ticket, attaching here as well. 
[ForWebPosting_09.12_NCP.MtgAgenda (UPDATED) v2.docx](https://github.com/user-attachments/files/16852190/ForWebPosting_09.12_NCP.MtgAgenda.UPDATED.v2.docx)

**Comment by meglake** [comment]
Hi @erikscottmeyer, there are a few addition edits from PCP, see below:

- They didn't realize that the Panel info they have in the documents does not match with the info on [NCI’s DEA webpage](https://deainfo.nci.nih.gov/advisory/pcp/pcp-members.pdf) – and it's required to. Please update the Panel info on the participant list for both the 12th and 13th to match the text in the attached document

- In https://prescancerpanel-dev.cancer.gov/pr-289/ncp/meetings/2024-09-12/part-1/  Change “Iowa City, Iowa” to “Iowa City, IA”

- In https://prescancerpanel-dev.cancer.gov/pr-289/ncp/meetings/2024-09-12/part-2/  Change “Durham, North Carolina” to “Durham, NC”

**Comment by meglake** [comment]
@erikscottmeyer PCP approved pages to go live!
