### ISSUE TITLE
PCP Sitemap - Update Navigation

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#47]
Update Navigation to reflect mock-ups

## AC

- Navigation tabs of active pages should be highlighted
- When a user hovers over a navigation tab, related sub pages should display and be clickable 

## Sub-Tasks
- [x] Home
- [x] Members ( and members bio pages)
- [x] About
    - Sub-pages - History
    - Sub-pages - Process
    - Sub-pages - Staff
    - Sub-pages - Blog
            -Sub-page - NCA 50th anniversary 
- [x] Reports & Meetings
 

## Resources
- Mural Mockups  - https://app.mural.co/t/worklifepage1864/m/worklifepage1864/1665585689544/22bc12c75257b9a87d068eb03dbda96d4f61d72e?sender=u391897c2e974e80931994272

![Image](https://user-images.githubusercontent.com/80473282/229594766-bcd7b34c-07a8-4d96-8b80-773083779460.png)

![Image](https://user-images.githubusercontent.com/80473282/229601978-a4e1ddbb-250b-4362-88e8-0732352af6c3.png)

- ...

**Comment by jfrank-nih** [comment]
This should be done in combination with #40. It will also involve implementing the left nav that we already have in place on additional pages.
