### ISSUE TITLE
PCP Members - Landing page

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#49]
Members Landing page 

- [x]  Add picture images for current members
- [x] Left align list of current members
- [x] Add Past Panel Members infographic
           - [ ] Add view more/ view less tabs for infographic display

**Resources**

[Mural Mockups](https://app.mural.co/t/worklifepage1864/m/worklifepage1864/1665585689544/22bc12c75257b9a87d068eb03dbda96d4f61d72e?sender=u391897c2e974e80931994272)

![Image](https://user-images.githubusercontent.com/80473282/229597497-3dd73042-927f-4915-b6a2-ef7e1205c8a3.png)

**Comment by jfrank-nih** [comment]
Adding images is covered under #39.
