### ISSUE TITLE
Homepage and Search - QA Findings

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#56]
@SupriyaSaxena0605 to add QA findings for Homepage and Search

**Comment by SupriyaSaxena0605** [comment]
@santwuma 
1. Members are displayed horizontally and not vertically as in mockups on Members page.
![image](https://user-images.githubusercontent.com/31008800/236038567-72d0b5cf-8e80-4c44-9358-db178fd78c1c.png)

2. Past members are missing on Members page
3. Space is needed between "Show" and "Count dropdown" and "results"
![image](https://user-images.githubusercontent.com/31008800/236041566-e9d44afb-29b5-475c-a0ee-076d6567ea8f.png)

4."RESULTS 1-20 OF 610 FOR: TUMOR" can be "Results 1-20 of 610 for: Tumor"
![image](https://user-images.githubusercontent.com/31008800/236042268-cb741981-48cf-4ac6-b356-098bd82acbf0.png)

**Comment by santwuma** [comment]
Disregard findings **1 and 2** for now as it relates to the members page which are out of scope for this testing. These will be addressed when we work on the members page. 

Fix **3 and 4** 

Also link on middle feature card is still broken "page not found" error displays

**Comment by erikscottmeyer** [comment]
@santwuma @SupriyaSaxena0605 
I addressed these issues in the PR for #53: 
Since we agreed about adding the Past Members image to members here it is:
https://prescancerpanel-dev.cancer.gov/pr-69/members
Here's search:
https://prescancerpanel-dev.cancer.gov/pr-69/search?swKeyword=cancer

**Comment by SupriyaSaxena0605** [comment]
Issues on Search:
1. The pager on Mobile is not displaying in the middle
![image](https://user-images.githubusercontent.com/31008800/236899993-3e8b45c8-4428-4a3b-9959-cb03a241dc57.png)

2.Space is needed here in the marked area
![image](https://user-images.githubusercontent.com/31008800/236900785-1e7407f3-9635-45f9-9967-d818ff486273.png)
