### ISSUE TITLE
Test Search with PCP site data before launch

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#68]
Run manual crawl on PCP site 

See here: https://prescancerpanel-dev.cancer.gov/pr-81/ (on VPN)

**Comment by SupriyaSaxena0605** [comment]
@santwuma This ticket looks good in dev.

**Comment by SupriyaSaxena0605** [comment]
@jfrank-nih The 0 results found page is displaying like this: 
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/bbd9c97d-8d72-45c4-9fbc-42b7bd2fd9d6)
I' will be logging another ticket for this issue.
Other than that, all looks good in PR-81 for this ticket
