### ISSUE TITLE
Add Adobe analytics script

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#7]
Implement Adobe anyalytics scripts on the page using Adobe launch. 

Paste this code inside the `<head>` tag of your document.

````
<script src="https://assets.adobedtm.com/6a4249cd0a2c/785de09de161/launch-70d67a6a40a8.min.js"></script>
````
Paste this code just before the closing </body> tag of your document.
````
<script type="text/javascript">_satellite.pageBottom();</script>
````

Also, update the search `input` to have an id of `searchbox-header-input`

**Comment by welshja** [comment]
I've made the changes in launch to setup for this site. Once this snippet is added, just let me know, and I can help with testing.
