### ISSUE TITLE
QA About Pages

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#93]
QA and loop in IA/design reviews.

**Comment by SupriyaSaxena0605** [comment]
QA issues:
1. History being a sub-page should have a different highlighting color than the "About" landing page on the left menu. 

![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/740927a1-5fdd-442c-bc47-683c536514f7)

**Comment by SupriyaSaxena0605** [comment]
2. When I switched to "Surface Duo" on Dev Tools, the banner is appearing as pixelated grid
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/5d25b22b-0a0d-460e-818b-ab0e3c5191b1)

**Comment by SupriyaSaxena0605** [comment]
3. Getting some console errors on the Staff page 
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/7f51b8ff-efcd-4b84-ba0b-9223f7379880)

**Comment by santwuma** [comment]
@erikscottmeyer to look into these except for 2.

**Comment by santwuma** [comment]
Done - bug in Microsoft
