### ISSUE TITLE
Fix navigation for mobile breakpoint

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#94]
The menu for the mobile view is not broken into two rows. Reports & Meetings is on a separate line

- [ ] Adjust padding for mobile and fix it

**Current behavior:**

![Image](https://user-images.githubusercontent.com/80473282/237496135-7f1396a2-980b-4108-9f6d-bda34de80b58.png)

**Expected behavior:** 

![Image](https://user-images.githubusercontent.com/80473282/237496970-8f28553e-7fd8-4d68-8756-d739668a1a24.png)

**Comment by SupriyaSaxena0605** [comment]
@erikscottmeyer 
navigation is still breaking for Iphone SE:
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/ee214424-f4b1-4cb0-857d-bbf5519cf6c0)

**Comment by santwuma** [comment]
@erikscottmeyer to look into it

**Comment by erikscottmeyer** [comment]
@SupriyaSaxena0605 @santwuma  This is fixed now for all devices in inspect (went through all pages of the site that way and resolved a few other problems too).  The only potential problem is that there was no way to fix this for Galaxy fold without reducing the font size for top navigation on mobile; it might be a bit small now.  We could restore the font size, with reduced padding, and it would work on everything but Galaxy fold, but if we need to support that device, we will have to either reduce the font-size (as I did), or abandon this approach and go back to the hamburger.

**Comment by erikscottmeyer** [comment]
Ok, I changed it as discussed to remove Home, make the to title and slogan links to home, and adjusted the text size for mobile (it's a little smaller than regular now, but larger than I had it before, and works across all devices).  I think this is the best approach that won't break on any of the devices in inspect.
