### ISSUE TITLE
Blogs: Clean up blog page

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#96]
There is a [spiked blog page](https://github.com/NCIOCPL/gatsby-pcp/blob/develop/src/pages/about/blogs.js) in `src/about/blogs.js`.

Some items that need to be improved:

- [ ] There may be a better graphQL query. I think `allSitePages` with a filter would return a prettier page URL, if we could figure out how to navigate to the frontmatter from that
- [ ] The rendering of the blog list needs to show title/description/date (like on [cancer currents](https://www.cancer.gov/news-events/cancer-currents-blog))
    - Open question: will blog posts ever not be authored by the whole panel? If not, then author is probably irrelevant
- [ ] Add the ability to show images
    - Images would need to be part of the frontmatter in order to query them onto the list page. Probably a new `image` line and a new `img alt text` line
    - Display would have to be added to `src/pages/about/blogs.js` and to `src/templates/blogs.js`
    - The [one current post](https://prescancerpanel.cancer.gov/2022-blogs/presidents-cancer-panel-commends-national-cancer-plan) does have an image to use

**Comment by santwuma** [comment]
@Sandra to follow-up on author fields for bogs
