### ISSUE TITLE
Move NCA 50 Location

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#97]
Currently NCA50 is located under `Blogs` in the menu on [About](https://prescancerpanel-dev.cancer.gov/develop/about/).

<img width="458" alt="image" src="https://github.com/NCIOCPL/gatsby-pcp/assets/93668289/55b2d8bb-0684-411c-bbf3-532725a6a087">

But it is just under `About` in the URL: `https://prescancerpanel-dev.cancer.gov/develop/about/nca50/`. That's because it has its own menu structure once you get into it.

**For Reference**: https://www.cancer.gov/news-events/cancer-currents-blog

Questions:

- [x] Where should NCA 50 be located in the menu? Under blogs or not?
- [ ] Where should NCA 50 be located in the URL? Should it match the menu?
- [ ] If NCA 50 is under blogs, do we want the pages from it to show up on the blogs list? All four or just the first one? 
    - Note for devs: I think if we made any one of the pages use the blogs template then it would show up, but this would probably break the left navigation on those pages.

_**Easiest Solution**_: May or may not be acceptable. Just turn those four pages into blog posts that show up in the blog list and _don't_ have their own custom navigation linking them together. This would just treat them as any other future blog post will be treated.

_**Second Easy Solution**_: Don't try to treat this as blogs at all. Put it under `About`, not under `Blogs` and don't have it show up in the blog list.

**Comment by santwuma** [comment]
Pending PCP Feedback.
