### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#98]
~~Gatsby has a breadcrumbs plugin that _should_ be easy to implement: https://www.gatsbyjs.com/plugins/gatsby-plugin-breadcrumb/?=bread%20crum~~

Do we want breadcrumbs? Is the site getting complex enough that they would be helpful?

The gatsby-plugin-breadcrumb plugin is not great.
- For one set of problems see #101
- For another problem see [this comment](https://github.com/NCIOCPL/gatsby-pcp/issues/98#issuecomment-1673879059)

I think the best route is probably to just detect the pages available to us going back up the URL path using the `/`s. That's similar to how we generate the [left navigation](https://github.com/NCIOCPL/gatsby-pcp/blob/develop/src/components/LeftNavigation.jsx). Basically, work back up the URL by removing one segment at a time from the end. _If there is a page that matches the URL we're checking_, then put it into the breakdcrumbs.

**Comment by santwuma** [comment]
Not doing it for MVP

**Comment by jfrank-nih** [comment]
I actually can get the click tracking version of this to work, but it is weird. It doesn't generate breadcrumbs based on the site hierarchy but based on what you've clicked on. So if you click down the list of a left-hand menu you will end up with all of those menu items in your breadcrumbs. I don't think it's a good way to go about this.

**Comment by SupriyaSaxena0605** [comment]
@santwuma @jfrank-nih this looks good on dev
![image](https://github.com/NCIOCPL/gatsby-pcp/assets/31008800/87692402-301b-4a1f-875f-659bd22e5483)
